# Generated by Django 6.0 on 2026-01-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smart_devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('device_type', models.CharField(default='light', max_length=50)),
                ('location', models.CharField(default='Phòng khách', max_length=100)),
                ('mqtt_topic', models.CharField(help_text='Topic MQTT duy nhất', max_length=255, unique=True)),
                ('current_status', models.CharField(default='OFF', max_length=50, verbose_name='Trạng thái hiện tại')),
                ('is_connected', models.IntegerField(default=0, verbose_name='Trạng thái kết nối (0: Tắt, 1: Bật)')),
                ('first_used', models.DateTimeField(auto_now_add=True, verbose_name='Lần đầu sử dụng')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Lần sử dụng cuối')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Lần bảo trì cuối')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
            ],
            options={
                'verbose_name': 'Thiết bị thông minh',
                'verbose_name_plural': 'Quản lý thiết bị',
            },
        ),
    ]
